import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#051424",
        "surface-dim": "#051424",
        "surface-bright": "#2c3a4c",
        "surface-container-lowest": "#010f1f",
        "surface-container-low": "#0d1c2d",
        "surface-container": "#122131",
        "surface-container-high": "#1c2b3c",
        "surface-container-highest": "#273647",
        "on-surface": "#d4e4fa",
        "on-surface-variant": "#d8c3ad",
        "inverse-surface": "#d4e4fa",
        "inverse-on-surface": "#233143",
        outline: "#a08e7a",
        "outline-variant": "#534434",
        "surface-tint": "#ffb95f",
        primary: "#ffc174",
        "on-primary": "#472a00",
        "primary-container": "#f59e0b",
        "on-primary-container": "#613b00",
        "inverse-primary": "#855300",
        secondary: "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        tertiary: "#8ed5ff",
        "on-tertiary": "#00354a",
        "tertiary-container": "#38bdf8",
        "on-tertiary-container": "#004965",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#051424",
        "on-background": "#d4e4fa",
        "surface-variant": "#273647",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ['"JetBrains Mono"', "monospace"],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2rem",
        margin: "1.25rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "4rem",
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "space-lg": "2.25rem",
        "space-xl": "3.5rem",
        "space-2xl": "5rem",
        "space-3xl": "8rem",
      },
    },
  },
  plugins: [],
};

export default config;
